# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.
# config/_default/menus.toml

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "Reviews"
  pageRef = "reviews"
  weight = 40

[[main]]
  name = "Philosophy"
  parent = "Blog"
  pageRef = "philosophy"
  weight = 30

[[main]]
  name = "Metaphysics"
  parent = "Blog"
  pageRef = "categories/Metaphysics"
  weight = 60

[[main]]
  name = "Video Essay"
  parent = "Blog"
  pageRef = "categories/video-essay"
  weight = 70

[[main]]
  name = "About Me"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Featured"
  pageRef = "categories/Featured"
  weight = 30

[[main]]
  name = "Social"
  weight = 40

[[main]]
  name = "Twitch"
  parent = "Social"
  url = "https://www.twitch.tv/ashwinbalajiab"
  weight = 10

[[main]]
  name = "YouTube"
  parent = "Social"
  url = "https://www.youtube.com/@ijustdontknowanymore0/featured"
  weight = 20

[[main]]
  name = "Instagram"
  parent = "Social"
  url = "https://www.instagram.com/ashwinbalaji00/"
  weight = 30

[[main]]
  name = "TikTok"
  parent = "Social"
  url = "http://tiktok.com/@ashwinbalaji02"
  weight = 40

[[footer]]
  name = "Privacy"
  pageRef = "privacy-policy"

[[footer]]
  name = "Impressum"
  pageRef = "impressum"

#[[footer]]
#  name = "Terms of Use"
#  url = "https://external-link"

#[[main]]
#  name = "Blog"
#  pageRef = "posts"
#  weight = 10

#[[main]]
#  name = "Parent"
#  weight = 20

[[main]]
  name = "Musings"
  parent = "Blog"
  pageRef = "categories/Musings"
  weight = 20

[[main]]
  name = "Physics"
  parent = "Blog"
  pageRef = "categories/Physics"
  weight = 10

[[main]]
  name = "Computers"
  parent = "Blog"
  pageRef = "categories/Computers"
  weight = 60

[[main]]
  name = "Book Reviews"
  parent = "Reviews"
  pageRef = "categories/Book-Review"
  weight = 10

[[main]]
  name = "Media Reviews"
  parent = "Reviews"
  pageRef = "categories/Media-Review"
  weight = 40

[[main]]
  name = "Mathematics"
  parent = "Blog"
  pageRef = "categories/Mathematics"
  weight = 30

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 30

[[footer]]
  name = "Categories"
  pageRef = "categories"
  weight = 20

[[footer]]
  name = "Blog"
  pageRef = "posts"
  weight = 10
